baseURL = "https://tukangcat.bangunan.co/"
languageCode = "id"
title = "Tukang Cat Tembok | Tukang Cat Tembok atau Cat Dinding Berpengalaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jasa Tukang Cat Tembok dan Dinding - Profesional, Berpengalaman, dan hasil yang Rapih"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa tukang cat", "cat dinding", "tukang cat berpengalaman", "cat tembok", "cat interior", "cat exterior"]
  base_price = 2000000
  price_range = 300000
  free_consultation = true
  service_types = [
  "Pengecatan Interior",
  "Pengecatan Eksterior",
  "Pengecatan Waterproof",
  "Pengecatan Anti Jamur",
  "Pengecatan Semprot"
  ]
  categories = ["Jasa Cat", "Tukang Cat", "Pengecatan"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Jasa dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya dapat dilakukan jika hasil tidak memuaskan.",
  "Revisi gratis untuk hasil pekerjaan yang kurang memuaskan."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Ruangan atau bangunan yang telah dicat sesuai permintaan"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Cat Tembok Profesional"
  hero_description = "Kami menawarkan layanan pengecatan tembok berkualitas dengan hasil rapi dan tahan lama. Solusi terbaik untuk memperindah tampilan rumah, kantor, atau properti Anda, dilakukan oleh tim tukang cat berpengalaman dan profesional."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Layanan Cat Tembok"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan jasa tukang cat tembok dengan kualitas pengerjaan terbaik dan biaya terjangkau. Anda bisa konsultasi secara gratis untuk membantu Anda memilih warna dan teknik cat yang sesuai dengan kebutuhan proyek Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "tukangcat.bangunan.co menawarkan jasa pengecatan tembok berkualitas, dengan fokus pada ketelitian, keindahan, dan ketahanan. Kami berkomitmen memberikan kepuasan pelanggan dengan hasil pengecatan yang rapi, cepat, dan tahan lama. Pilih kami untuk memenuhi kebutuhan cat dinding rumah, kantor, atau properti Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Eko|Rudi|Andi|Hendra|Fajar|Samsul|Agus|Dedi|Joko}"
  message = "{Saya menggunakan jasa {pengecatan|tukang cat} dari tukangcat.bangunan.co untuk {rumah|hunian} saya, dan hasilnya {sangat memuaskan|luar biasa|benar-benar bagus}. Pengecatannya {sangat rapi|bersih dan rapi|rapi sekali} dan hasilnya {sangat memuaskan|benar-benar memuaskan|sesuai harapan}.|Pengecatan dinding rumah saya dilakukan oleh tukangcat.bangunan.co, dan saya {sangat puas|senang|terkesan} dengan hasilnya. Pekerjaan mereka {rapi|cepat dan rapi|sangat baik} serta {memuaskan|membuat rumah terlihat baru|benar-benar berkualitas}.}"
  response = "{Terima kasih atas {kepercayaannya|ulasan positifnya}! Kami {senang|gembira} dapat memberikan hasil pengecatan {yang memuaskan|terbaik|berkualitas tinggi} untuk rumah Anda.|Kami sangat menghargai ulasan dari Anda. Terima kasih telah mempercayakan pengecatan kepada kami.|Terima kasih atas kepercayaan Anda! Kami selalu berusaha memberikan hasil {terbaik|terpuji|memuaskan}.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Lina|Maya|Nina|Putri|Ratna|Ika}"
  message = "{tukangcat.bangunan.co {sangat membantu|membantu sekali} dalam memilih {warna|cat} dan {melakukan pengecatan|mengecat} dinding rumah saya. Hasilnya {sangat rapi|rapi sekali|bersih} dan sesuai dengan {keinginan|ekspektasi|rencana} saya.|Saya merasa sangat terbantu oleh tukangcat.bangunan.co dalam memilih warna cat untuk rumah saya. Pengecatan dilakukan {secara rapi|dengan rapi|sangat rapi} dan hasil akhirnya benar-benar {sesuai harapan|indah|bagus}.}"
  response = "{Kami sangat {menghargai|berterima kasih atas} ulasan Anda. Senang mendengar bahwa Anda {puas|sangat senang|terkesan} dengan hasil pengecatan kami.|Terima kasih atas ulasannya. Kami {gembira|senang} dapat memberikan hasil sesuai dengan keinginan Anda.|Terima kasih atas kepercayaannya. Kami akan terus berusaha memberikan hasil terbaik.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Budi|Rudi|Andi|Eko|Hendra|Fajar|Samsul|Agus|Dedi}"
  message = "{Hasil pengecatan dari tukangcat.bangunan.co {sangat rapi|bersih dan rapi|rapi sekali} dan {sesuai dengan harapan|benar-benar sesuai ekspektasi|sesuai keinginan} saya. Pekerjaan dilakukan dengan {cepat|profesional|cekatan} dan {sangat baik|berkualitas|memuaskan}.|Pekerjaan pengecatan yang dilakukan oleh tukangcat.bangunan.co {luar biasa|benar-benar bagus|sangat memuaskan}. Hasil pengecatannya {rapi|bersih|sesuai} dan sesuai {keinginan|harapan|ekspektasi} saya.}"
  response = "{Terima kasih, Kami {berkomitmen|selalu berusaha} memberikan layanan pengecatan {berkualitas|terbaik|memuaskan} dengan hasil {rapi|indah|terbaik}.|Kami sangat menghargai kepercayaan Anda. Senang mendengar Anda {puas|terkesan} dengan hasil kerja kami.|Terima kasih atas ulasannya, Kami senang bisa memberikan hasil pengecatan yang memuaskan.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Budi|Eko|Rudi|Fajar|Hendra|Agus|Dedi|Samsul|Joko}"
  message = "{Saya sangat puas dengan hasil {cat tembok|pengecatan} dari tukangcat.bangunan.co. Tembok terlihat lebih {segar|baru|cerah} dan {berkualitas|indah|bagus}.|Layanan pengecatan dari tukangcat.bangunan.co {sangat baik|memuaskan|terbaik}. Hasil akhirnya {sangat memuaskan|benar-benar memuaskan|luar biasa}. Tembok rumah saya sekarang {terlihat lebih baru|nampak lebih segar|lebih cantik} dan {rapi|bersih|bagus}}."
  response = "{Senang mendengar Anda {puas|sangat senang} dengan layanan kami. Terima kasih atas {kepercayaannya|ulasan positifnya}!|Terima kasih, atas {kepercayaannya|kerja samanya}! Kami senang bisa memberikan hasil pengecatan yang {terbaik|berkualitas tinggi|memuaskan}.|Terima kasih, kami {senang|gembira} dapat menyediakan layanan yang {memuaskan|berkualitas tinggi}.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Dewi|Ayu|Siti|Lina|Nina|Maya|Putri|Ratna|Ika}"
  message = "{{Pelayanan|Layanan} tukangcat.bangunan.co {sangat memuaskan|benar-benar baik|memuaskan sekali}. Hasil pengecatan dinding {sangat berkualitas|luar biasa|berkualitas tinggi} dan {sesuai dengan yang saya harapkan|benar-benar sesuai harapan|memenuhi ekspektasi saya}.|tukangcat.bangunan.co memberikan pelayanan {memuaskan|baik|terbaik}. Hasil pengecatan sangat {baik|rapi|berkualitas} dan sesuai dengan {keinginan|ekspektasi|rencana} saya.}"
  response = "{Terima kasih! Kami {senang|gembira} dapat membantu mewujudkan {proyek|impian} pengecatan Anda dengan {hasil terbaik|hasil berkualitas|hasil yang memuaskan}.|Kami sangat berterima kasih atas {kepercayaannya|kepercayaannya kepada kami}. Senang bisa memberikan hasil {yang memuaskan|terbaik|berkualitas} untuk Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Budi|Andi|Rudi|Agus|Joko|Hendra|Fajar|Dedi|Samsul}"
  message = "{Pengecatan tembok dari tukangcat.bangunan.co {sangat sesuai dengan|benar-benar memenuhi} {kebutuhan renovasi|keperluan renovasi|proyek renovasi} rumah saya. Pengerjaannya {cepat|tepat waktu|efisien} dan {rapi|bersih|baik sekali}.|Saya {puas|terkesan|sangat senang} dengan pengecatan tembok dari tukangcat.bangunan.co. Hasilnya {sesuai|tepat} dengan {renovasi|rencana renovasi} rumah saya, pengerjaannya {cepat|efisien} dan sangat {rapi|bersih}}."
  response = "{Kami senang mendengar bahwa Anda {puas|terkesan|sangat senang} dengan layanan pengecatan kami. Terima kasih atas {ulasannya|feedback positifnya}!|Terima kasih atas ulasannya! Kami senang bisa memberikan hasil pengecatan yang {memuaskan|berkualitas tinggi|rapi dan cepat}.}"
  rating = 5

[[params.tabelItems]]
  name = "Cat Tembok Interior"
  price = "80.000 /m"
[[params.tabelItems]]
  name = "Cat Tembok Eksterior"
  price = "250.000 /m"
[[params.tabelItems]]
  name = "Cat Waterproof"
  price = "300.000 /m"
[[params.tabelItems]]
  name = "Cat Anti Jamur"
  price = "180.000 /m"
[[params.tabelItems]]
  name = "Cat Semprot"
  price = "210.000 /m"

[params.appliList]
  "Cat Tembok Interior" = "ruang tamu, kamar tidur, dapur"
  "Cat Tembok Eksterior" = "fasad bangunan, teras, dinding luar"
  "Cat Waterproof" = "area lembab, kamar mandi, dapur"
  "Cat Anti Jamur" = "area rawan jamur, ruang lembab"
  "Cat Semprot" = "permukaan luas, dinding besar"

[params.kegunaanList]
  "Cat Tembok Interior" = "memberikan warna dan suasana yang nyaman"
  "Cat Tembok Eksterior" = "melindungi dinding dari cuaca dan memperindah tampilan"
  "Cat Waterproof" = "mencegah kebocoran dan kerusakan akibat air"
  "Cat Anti Jamur" = "menghindari pertumbuhan jamur pada dinding"
  "Cat Semprot" = "mempercepat proses pengecatan pada area besar"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Jasa Tukang Cat Tembok Rumah & Gedung Berpengalaman | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"